name: monitoring_hidroponik_flutter
description: "TA Sistem Monitoring Instalasi Hidroponik menggunakan LoRaWAN dan Framework Flutter"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^10.10.6
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  firebase_database: ^10.5.6
  flutter_bloc: ^8.1.5
  go_router: ^14.1.3
  intl: ^0.19.0
  mqtt_client: ^10.2.1
  shared_preferences: ^2.2.3
  syncfusion_flutter_charts: ^25.2.5
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: true
