name: monitoring_hidroponik_flutter
description: "TA Sistem Monitoring Instalasi Hidroponik menggunakan LoRaWAN dan Framework Flutter"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_database: ^10.5.2
  go_router: ^13.2.4
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  syncfusion_flutter_charts: ^25.1.40
  url_strategy: ^0.2.0
  firebase_analytics: ^10.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: true
