name: monitoring_hidroponik_flutter
description: "TA Sistem Monitoring Instalasi Hidroponik menggunakan LoRaWAN dan Framework Flutter"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.16.0
  firebase_core: ^2.28.0
  firebase_database: ^10.5.0
  fl_chart: ^0.67.0
  go_router: ^13.2.2
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
